import Head from "next/head";
import Link from "next/link";
import React from "react";

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + " | SLEAK " : "SLEAK"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex justify-between items-center h-16 bg-white text-black relative shadow-sm font-mono">
            <Link href="/" className="pl-8 text-lg font-bold">
              SLEAK
            </Link>
            <div className="px-4 cursor-pointer md:hidden">
              <svg
                className="w-6 h-6"
                fill="none"
                stroke="red"
                viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M4 6h16M4 12h8m-8 6h16"
                ></path>
              </svg>
            </div>
            <div className="pr-8 md:block hidden">
              <Link className="p-4" href="/">
                Cart
              </Link>
              <Link className="p-4" href="/">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="contianer m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center bg-white text-black shadow-sm font-mono">
            <p className="p-4">© 2023 SLEAK</p>
        </footer>
      </div>
    </>
  );
}
