import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Karam Isa',
      email: 'karam_isa@icloud.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Mo',
      email: 'mo@icloud,com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    }
  ],
    products: [
      {
        name: 'Shirt + Shorts',
        slug: 'shirt-shorts',
        category: 'Shirts',
        image: '/images/clothing1.jpeg',
        price: 70,
        brand: 'Habibi',
        rating: 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'A popular shirt',
        isFeatured: true,
        banner: '',
      },
      {
        name: 'Long Sleeve Shirt',
        slug: 'long-sleeve-shirt',
        category: 'Shirts',
        image: '/images/clothing2.jpeg',
        price: 80,
        brand: 'Habibi Excotics',
        rating: 3.2,
        numReviews: 10,
        countInStock: 20,
        description: 'A popular shirt',
        isFeatured: true,
        banner: '',
      },
      {
        name: 'Long Sleeve White Shirt',
        slug: 'long-sleeve-white-shirt',
        category: 'Shirts',
        image: '/images/clothing3.jpeg',
        price: 90,
        brand: 'Habibi Excotics',
        rating: 4.5,
        numReviews: 3,
        countInStock: 20,
        description: 'A popular shirt',
      },
      {
        name: 'Hoodie',
        slug: 'hoodie',
        category: 'Shirts',
        image: '/images/pants1.jpg',
        price: 90,
        brand: 'Oliver',
        rating: 2.9,
        numReviews: 13,
        countInStock: 20,
        description: 'Smart looking pants',
      },
      {
        name: 'Fit Pants',
        slug: 'fit-pants',
        category: 'Pants',
        image: '/images/pants2.jpg',
        price: 95,
        brand: 'Zara',
        rating: 3.5,
        numReviews: 7,
        countInStock: 20,
        description: 'A popular pants',
      },
      {
        name: 'Classic Pants',
        slug: 'classic-pants',
        category: 'Pants',
        image: '/images/pants3.jpg',
        price: 75,
        brand: 'Casely',
        rating: 2.4,
        numReviews: 14,
        countInStock: 20,
        description: 'A popular pants',
      },
    ],
  };
  
  export default data;